import pygame

# CONSTANTS
EXIT, STARTING, RUNNING, PAUSE = 0, 1, 2, 3
MAX_VEL = 1000
G = 3000 # gravitational acceleration
SPAWN_INTERVAL = 2000 # 2 seconds
ENEMY_SPAWN_EVENT = pygame.USEREVENT + 1
UPWARD_THRUST = -1000
HIGH_SCORE = 0
SCORE_FILE_PATH = "scores.csv"
MIN_ENEMY_HEIGHT = 40
MAX_ENEMY_HEIGHT = 100
ENEMY_RECT_AREA = 3000
MIN_ENEMY_WIDTH = ENEMY_RECT_AREA // MAX_ENEMY_HEIGHT
MAX_ENEMY_WIDTH = ENEMY_RECT_AREA // MIN_ENEMY_HEIGHT
ENEMY_VEL = -300

SC_WIDTH = 800
SC_HEIGHT = 600
SC_CENTER = pygame.Vector2(SC_WIDTH/2, SC_HEIGHT/2)
